ALTER TABLE `ep_remedy_class`
ADD COLUMN `grade_pass` INT(10) NOT NULL COMMENT 'nilai minimum' AFTER `course_subject_id`,
CHANGE COLUMN `id` `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
CHANGE COLUMN `sid` `sid` INT(11) UNSIGNED NOT NULL COMMENT 'student.id' AFTER `id`,
CHANGE COLUMN `ayid` `ayid` INT(11) UNSIGNED NOT NULL COMMENT 'academic_year.id' AFTER `sid`,
CHANGE COLUMN `tid` `tid` INT(11) UNSIGNED NOT NULL COMMENT 'rf_term.id' AFTER `ayid`,
CHANGE COLUMN `eid` `eid` INT(10) UNSIGNED NOT NULL AFTER `tid`,
CHANGE COLUMN `eid_remedy` `eid_remedy` INT(10) UNSIGNED NOT NULL AFTER `eid`,
CHANGE COLUMN `ayid_remedy` `ayid_remedy` INT(10) UNSIGNED NOT NULL AFTER `eid_remedy`,
CHANGE COLUMN `tid_remedy` `tid_remedy` INT(11) UNSIGNED NOT NULL AFTER `ayid_remedy`,
CHANGE COLUMN `course_subject_id` `course_subject_id` INT(11) UNSIGNED NOT NULL COMMENT 'subject.id' AFTER `tid_remedy`,
CHANGE COLUMN `grade_before` `grade_before` INT(10) UNSIGNED NOT NULL AFTER `grade_pass`,
CHANGE COLUMN `grade_after` `grade_after` INT(10) UNSIGNED NOT NULL AFTER `grade_before`,
CHANGE COLUMN `is_passed` `is_passed` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' AFTER `grade_after`,
CHANGE COLUMN `cby` `cby` INT(11) NOT NULL COMMENT 'Created By = uid' AFTER `is_passed`,
CHANGE COLUMN `uby` `uby` INT(11) NOT NULL COMMENT 'Updated By = uid' AFTER `cby`,
CHANGE COLUMN `con` `con` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created On' AFTER `uby`,
CHANGE COLUMN `uon` `uon` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated On' ON UPDATE CURRENT_TIMESTAMP AFTER `con`
