DROP TABLE IF EXISTS `ep_subject_diknas`;

CREATE TABLE `ep_subject_diknas` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ayid` INT(11) NOT NULL,
  `level` INT(11) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `group` VARCHAR(100) DEFAULT NULL,
  `seq` INT(2) DEFAULT NULL,
  `cby` INT(11) NOT NULL COMMENT 'Created By = uid',
  `uby` INT(11) NOT NULL COMMENT 'Updated By = uid',
  `con` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created On',
  `uon` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated On',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;